
--Exploratory Data Analysis

--1) Database exploration

--Explore All objects in database

SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore all Columns in database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'dim_customers'


-- 2) Dimension Exploeration -- Identifying unique values(or categories) in each dimension

--Explore all countries that our customer came from

SELECT DISTINCT country FROM gold.dim_customers


--Explore all categories 'The major division'

SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3

--3) Date Exploration

--Find the date of the first and last order

SELECT MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the oldest and youngest cust

SELECT MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

--4) Measure Exploration ( Calculate key metric of the business(Big Numbers)

--Find total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales
--Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales
--Find the avg selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales
--Find total no of orders
SELECT COUNT(order_number) AS total_order FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_order FROM gold.fact_sales --Always use this to avoid duplicates
--Find total no of products
SELECT COUNT(DISTINCT product_key) AS total_product FROM gold.fact_sales
--Find total no of customers
SELECT COUNT( DISTINCT customer_key) AS total_customer FROM gold.fact_sales
--Find total no of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customer FROM gold.fact_sales

--Generate a report that shows all key metrics of the business for the above

SELECT 'Total Sales' AS measure_name, SUM(CAST(sales_amount AS BIGINT)) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(CAST(quantity AS BIGINT)) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Order' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Product' AS measure_name, COUNT( product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Customer' AS measure_name, COUNT( customer_key) AS measure_value FROM gold.dim_customers

-- 5) Magnitude -- Compare the measure values by categories

--Find total customers by country

SELECT country,COUNT(customer_key) AS total_customers FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender

SELECT gender,COUNT(customer_key) AS total_customers FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category

SELECT category,COUNT(product_key) AS total_product FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- What is the avg cost in each category?

SELECT category,AVG(cost) AS avg_cost FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated for each category?

SELECT p.category, SUM(CAST(f.sales_amount AS BIGINT)) total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue is generated by each customer


SELECT c.customer_key,c.first_name,c.last_name,
SUM(CAST(f.sales_amount AS BIGINT)) total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?

SELECT c.country,
SUM(f.quantity ) total_sold_items FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

--6) Ranking  -- Orders the values of dimensions by measure

-- Which 5 products generate the highest revenue?

SELECT TOP 5 p.subcategory, SUM(CAST(f.sales_amount AS BIGINT)) total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

--Using window func
SELECT * FROM (
SELECT p.product_name, SUM(CAST(f.sales_amount AS BIGINT)) total_revenue,
ROW_NUMBER() OVER( ORDER BY SUM(CAST(f.sales_amount AS BIGINT)) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name)t
WHERE rank_products <= 5

-- What are the 5 worst performing products in terms of sales

SELECT TOP 5 p.product_number, SUM(CAST(f.sales_amount AS BIGINT)) total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_number
ORDER BY total_revenue 







